plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.linda.leetris'
    compileSdk 36
    buildToolsVersion '36.1.0'

    defaultConfig {
        applicationId 'com.nyoka.linda.leetris'
        minSdk 15
        targetSdk 36
        versionCode 1
        versionName '1.0'
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
}
